import Header from "@/common/header";
import "./globals.css";
import Sidebar from "@/common/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-bgblack text-white">
        <main className="grid grid-cols-[280px_1fr] h-screen">
          <div className="w-full">
            <Sidebar />
          </div>
          <div className="w-full">
            <Header />
            <div className="h-[calc(100%-63px)] overflow-y-auto">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
